// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/cj-dropshipping/CJAcademy.tsx": () => import("../components/mockups/cj-dropshipping/CJAcademy.tsx"),
  "./components/mockups/cj-dropshipping/CJBlog.tsx": () => import("../components/mockups/cj-dropshipping/CJBlog.tsx"),
  "./components/mockups/cj-dropshipping/CJCheckout.tsx": () => import("../components/mockups/cj-dropshipping/CJCheckout.tsx"),
  "./components/mockups/cj-dropshipping/CJFindProducts.tsx": () => import("../components/mockups/cj-dropshipping/CJFindProducts.tsx"),
  "./components/mockups/cj-dropshipping/CJHomepage.tsx": () => import("../components/mockups/cj-dropshipping/CJHomepage.tsx"),
  "./components/mockups/cj-dropshipping/CJLogin.tsx": () => import("../components/mockups/cj-dropshipping/CJLogin.tsx"),
  "./components/mockups/cj-dropshipping/CJPodcast.tsx": () => import("../components/mockups/cj-dropshipping/CJPodcast.tsx"),
  "./components/mockups/cj-dropshipping/CJProductDetail.tsx": () => import("../components/mockups/cj-dropshipping/CJProductDetail.tsx"),
  "./components/mockups/cj-dropshipping/CJServices.tsx": () => import("../components/mockups/cj-dropshipping/CJServices.tsx"),
  "./components/mockups/cj-dropshipping/CJSourceForMe.tsx": () => import("../components/mockups/cj-dropshipping/CJSourceForMe.tsx"),
  "./components/mockups/cj-dropshipping/CJWarehouse.tsx": () => import("../components/mockups/cj-dropshipping/CJWarehouse.tsx")
};
